export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const LOAD_ALL_DEALS = 'LOAD_ALL_DEALS';
export const LOAD_ALL_DEALS_SUCCESS = 'LOAD_ALL_DEALS';
export const LOAD_ALL_DEALS_ERROR = 'LOAD_ALL_DEALS_ERROR';
